# Generated by Django 2.2.13 on 2021-03-22 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='main', max_length=255)),
                ('paragraph', models.CharField(default='para', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('expiry', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
