# Generated by Django 2.2.13 on 2021-03-22 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('parent_id', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('key', models.PositiveIntegerField()),
            ],
        ),
    ]
