# Generated by Django 2.2.13 on 2021-02-22 07:27

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_latest', models.BooleanField(default=False, verbose_name='Is Latest')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('last_address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('totalprice', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='Order status')),
                ('invoice_number', models.PositiveIntegerField()),
                ('delivery_address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Address')),
            ],
        ),
    ]
