# Generated by Django 2.2.13 on 2021-03-22 03:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_address.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.DJANGO_ADDRESS_ADDRESS_MODEL),
        ('products', '__first__'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancelReason', models.CharField(default='delayed', max_length=255)),
                ('cancelledOn', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 22, 3, 57, 46, 437730))),
                ('customer_email', models.EmailField(default='example@gmail.com', max_length=255, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='Order status')),
                ('customer_id', models.ForeignKey(default=uuid.UUID('c2fab692-8ac2-11eb-9f8c-b7f9c42d9eae'), on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('delivery_address', django_address.fields.AddressField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_ADDRESS_ADDRESS_MODEL, verbose_name='Delivery address')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
