# Generated by Django 2.2.13 on 2021-03-24 03:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210324_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelledOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 3, 26, 49, 514471)),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=uuid.UUID('c4fe4b5e-8c50-11eb-bdb0-f5555760d940'), on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
