# Generated by Django 2.2.13 on 2021-03-24 03:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210324_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelledOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 3, 29, 24, 281418)),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=uuid.UUID('213dd204-8c51-11eb-95de-6741ae781871'), on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
