# Generated by Django 2.2.13 on 2021-03-24 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210324_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelledOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 4, 50, 36, 44504)),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=uuid.UUID('7909dce8-8c5c-11eb-8310-cdd9419d2f37'), on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
