# Generated by Django 2.2.13 on 2021-03-24 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210324_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelledOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 5, 12, 41, 456121)),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=uuid.UUID('8f226f42-8c5f-11eb-93a4-9dd22bb0ece6'), on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
