# Generated by Django 2.2.13 on 2021-03-24 04:03

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_extensions.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('category', '0001_initial'),
        ('varient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category_path', django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=515), blank=True,  null=True, size=None)),
                ('category_rank', models.PositiveIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('desciption', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('brand', models.CharField(default='', max_length=255)),
                ('more_prop', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('tags', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Seller')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('insertedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('varient_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='varient.Varient')),
            ],
        ),
    ]
