# Generated by Django 2.2.13 on 2021-03-22 03:59

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_path',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=515), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_prop',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=515), blank=True,  null=True, size=None),
        ),
    ]
