# Generated by Django 2.2.13 on 2021-03-24 04:50

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210324_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_path',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=515), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_prop',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=515), blank=True, null=True, size=None),
        ),
    ]
