# Generated by Django 2.2.13 on 2021-03-24 05:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210324_0450'),
    ]

    

    operations = [
    migrations.RemoveField(
        model_name='product',
        name='more_prop',
    ),
    migrations.AddField(
        model_name='product',
        name='more_prop',
        field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
    ),
    ]   
